CREATE TEMPORARY EXTERNAL TABLE IF NOT EXISTS tARTar78.hw2_test (
    id INT,
    if_1 INT, if_2 INT, if_3 INT, if_4 INT, if_5 INT, if_6 INT, if_7 INT, if_8 INT, if_9 INT, if_10 INT,
    if_11 INT, if_12 INT, if_13 INT,
    cf_1 STRING, cf_2 STRING, cf_3 STRING, cf_4 STRING, cf_5 STRING, cf_6 STRING,
    cf_7 STRING, cf_8 STRING, cf_9 STRING, cf_10 STRING, cf_11 STRING, cf_12 STRING,
    cf_13 STRING, cf_14 STRING, cf_15 STRING, cf_16 STRING, cf_17 STRING, cf_18 STRING,
    cf_19 STRING, cf_20 STRING, cf_21 STRING, cf_22 STRING, cf_23 STRING, cf_24 STRING,
    cf_25 STRING, cf_26 STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION "/datasets/criteo/testdir";
